version: '3.5'

services:

    #EarnApp Configuration
    earnapp:
        container_name: earnapp
        image: fazalfarhan01/earnapp:lite
        restart: always
        environment:
            - EARNAPP_UUID=${YOUR_EARNAPP_NODE_ID}
        networks:
            default:
                ipv4_address: 172.106.0.10
    #end of EarnApp Configuration

    #HoneyGain Configuration
    honeygain:
        container_name: honeygain
        image: honeygain/honeygain
        command: -tou-accept -email '${YOUR_HONEYGAIN_EMAIL_ADDRESS}' -pass '${YOUR_USER_HONEYGAIN_PASSWORD}' -device p-income
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.20
    #end of HoneyGain Configuration

    #Peer2Profit Configuration
    peer2profit:
        container_name: peer2profit
        image: enwaiax/peer2profit:latest
        restart: always
        environment:
            - email=${YOUR_PEER2PROFIT_EMAIL_ADDRESS}
            - use_proxy=false
        networks:
            default:
                ipv4_address: 172.106.0.30
    #end of Peer2Profit Configuration

    #PacketStream Configuration
    psclient:
        container_name: psclient
        image: packetstream/psclient:latest
        restart: always
        environment:
            - CID=${YOUR_PACKETSTREAM_CID}
        networks:
            default:
                ipv4_address: 172.106.0.40

    pswatchtower:
        depends_on:
            - psclient
        image: containrrr/watchtower
        container_name: pswatchtower
        command: --cleanup --include-stopped --revive-stopped --interval 60 earning-machine_psclient_1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.41
    #end of PacketStream Configuration

    #Pawns Configuration
    pawns:
        container_name: pawn        
        image: iproyal/pawns-cli:latest
        command: -email='${YOUR_PAWNS_EMAIL_ADDRESS}' -password='${YOUR_PAWNS_USER_PASSWORD}' -device-name=p-income -accept-tos
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.50
    #end of Pawns Configuration
    
    #Bitping Configuration
    bitping:
        container_name: bitping
        image: bitping/bitping-node:latest
        restart: always
        volumes:
            - ./data/bitping:/root/.bitping
        networks:
            default:
                ipv4_address: 172.106.0.60
    #end of Bitping Configuration

    #TraffMonetizer Configuration
    traffmonetizer:
        container_name: traffmonetizer
        image: traffmonetizer/cli:latest
        restart: always
        command: start accept --token ${YOUR_TRAFFMONETIZER_TOKEN}
        networks:
            default:
                ipv4_address: 172.106.0.70
    #end of TraffMonetizer Configuration

    #Repocket Configuration
    repocket:
        container_name: repocket
        image: repocket/repocket:latest
        restart: always
        environment:
           - RP_EMAIL=${YOUR_REPOCKET_EMAIL_ADDRESS}
           - RP_API_KEY=${YOUR_REPOCKET_API_KEY}
        networks:
            default:
                ipv4_address: 172.106.0.80
    #end of Repocket Configuration

    #Proxylite Configuration
    proxylite:
        container_name: proxylite
        image: proxylite/proxyservice:latest
        restart: always
        environment:
          - USER_ID=${YOUR_PROXYLITE_ACCOUNT_ID}
        networks:
            default:
                ipv4_address: 172.106.0.90
    #end of Proxylite Configuration

    #ProxyRack Configuration
    proxyrack:
        container_name: proxyrack
        image: proxyrack/pop:latest
        restart: always
        environment:
          - api_key=${YOUR_PROXYRACK_API_KEY}
          - device_name=p-income
        networks:
            default:
                ipv4_address: 172.106.0.100
    #end of ProxyRack Configuration

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.106.0.0/16